Repository insaroule/insaroule, pull requests merged in 2025-08, with the labels that each got.

#158 translations for chat
  project/carpool/templates/rides/detail.html
  project/chat/locale/fr/LC_MESSAGES/django.po
  project/chat/templates/chat/includes/mod_profile.html
  project/chat/templates/chat/includes/sidebar.html
  project/chat/templates/chat/index.html
  project/chat/templates/chat/moderation/index.html
  project/chat/templates/chat/moderation/room.html
  project/chat/templates/chat/moderation/search.html
  project/chat/templates/chat/room.html
Labels: i18n

#178 Fix (#164) departure arrival grey on rides list
  project/accounts/locale/fr/LC_MESSAGES/django.po
  project/carpool/locale/fr/LC_MESSAGES/django.po
  project/carpool/templates/rides/list.html
  project/chat/locale/LC_MESSAGES/django.po
Labels: frontend

#180 Add translation for ride_create view
  project/carpool/forms.py
  project/carpool/locale/fr/LC_MESSAGES/django.po
  project/carpool/templates/rides/create.html
Labels: i18n

#181 Major improvements for chat and fix creating ride
  .env.dist
  project/carpool/templates/rides/detail.html
  project/carpool/views.py
  project/chat/templates/chat/includes/sidebar.html
  project/chat/templates/chat/index.html
Labels: bug, enhancement, frontend, backend, chat

#190 Debug task to test celery access to envvars
  project/accounts/tasks.py
Labels: bug

#210 Fix using insecure ws instead of wss with https
  project/chat/templates/chat/room.html
Labels: bug, chat, deployment

#214 i18n inclusion in french for username field
  project/accounts/locale/fr/LC_MESSAGES/django.po
  project/accounts/templates/registration/login.html
Labels: frontend, i18n

#229 Unread messages emails notification
  .env.dist
  project/carpool/migrations/0003_alter_vehicle_driver_alter_vehicle_name.py
  project/chat/consumers.py
  project/chat/locale/LC_MESSAGES/django.po
  project/chat/locale/fr/LC_MESSAGES/django.po
  project/chat/migrations/0002_chatmessage_notified_at_chatmessage_read_at.py
  project/chat/models.py
  project/chat/tasks.py
  project/chat/templates/chat/emails/unread_messages.txt
  project/chat/templates/chat/index.html
  project/chat/templates/chat/room.html
  project/project/celery.py
  project/project/settings/development.py
  project/project/settings/production.py
  project/templates/emails/consent_footer.txt
  project/templates/emails/mandatory_footer.txt
  project/templates/emails/signature.txt
  pyproject.toml
Labels: backend, chat

#216 Add persistent filter on search page to avoid having to retype every…
  project/carpool/templates/rides/list.html
Labels: frontend

#232 Set maximum price per seat at 999 €
  project/carpool/forms.py
  project/carpool/templates/rides/create.html
  project/carpool/templates/rides/edit.html
Labels: bug, frontend

#234 Filter out rides that are in the past
  project/carpool/views.py
Labels: frontend

#238 favicons and logs in production settings
  project/project/settings/production.py
  project/project/urls.py
  project/templates/base.html
Labels: enhancement, frontend, deployment

#242 Improved emails and translation
  project/accounts/locale/fr/LC_MESSAGES/django.po
  project/accounts/tasks.py
  project/accounts/templates/account/data_export_email.txt
  project/accounts/templates/registration/verify_email/emails/verify_email.txt
  project/carpool/locale/fr/LC_MESSAGES/django.po
  project/chat/locale/fr/LC_MESSAGES/django.po
  project/chat/tasks.py
  project/chat/templates/chat/emails/unread_messages.txt
  project/locale/fr/LC_MESSAGES/django.po
  project/templates/emails/consent_footer.txt
  project/templates/emails/mandatory_footer.txt
Labels: frontend, i18n

#248 My rides
  project/carpool/templates/rides/includes/pagination.html
  project/carpool/templates/rides/includes/ride_card.html
  project/carpool/templates/rides/my_rides.html
  project/carpool/views.py
Labels: enhancement, frontend, backend

#251 Report Issue button to contact support
  .env.dist
  project/locale/fr/LC_MESSAGES/django.po
  project/project/context_processors.py
  project/project/settings/production.py
  project/templates/includes/navbar.html
Labels: enhancement, frontend, backend, deployment

#254 Notification preferences
  project/accounts/admin.py
  project/accounts/apps.py
  project/accounts/migrations/0002_usernotificationpreferences.py
  project/accounts/models.py
  project/accounts/signals.py
  project/accounts/templates/account/detail.html
  project/accounts/views/profile.py
  project/chat/tasks.py
Labels: gdpr, chat, deployment

#259 Pagination for chats
  project/chat/templates/chat/includes/sidebar.html
  project/chat/templates/chat/includes/sidebar_item.html
  project/chat/views.py
Labels: bug, frontend, backend
