Repository insaroule/insaroule, pull requests merged in 2025-05, with the labels that each got.

#38 fix(ci) update workflow to run ci when pr on develop branch
  .github/workflows/django.yml
Labels: enhancement, ci/cd

#36 feat(carpool) : Ride list view fixes #5
  project/accounts/templates/register.html
  project/carpool/admin.py
  project/carpool/migrations/0003_location_ride_payment_method_ride_price_ride_rider_and_more.py
  project/carpool/models.py
  project/carpool/templates/rides/list.html
  project/carpool/views.py
Labels: enhancement, frontend, backend

#39 Carpool models
  .github/workflows/django.yml
  project/accounts/templates/register.html
  project/carpool/admin.py
  project/carpool/migrations/0003_location_ride_payment_method_ride_price_ride_rider_and_more.py
  project/carpool/models.py
  project/carpool/templates/rides/list.html
  project/carpool/views.py
Labels: enhancement, backend

#40 improve login template
  project/accounts/templates/login.html
Labels: frontend
