Repository insaroule/insaroule, pull requests merged in 2025-07, with the labels that each got.

#64 feat(accounts) account detail and password management
  project/accounts/admin.py
  project/accounts/forms.py
  project/accounts/models.py
  project/accounts/tasks.py
  project/accounts/templates/account/detail.html
  project/accounts/templates/account/email_change.html
  project/accounts/templates/account/password_change.html
  project/accounts/templates/registration/login.html
  project/accounts/templates/registration/password_reset/complete.html
  project/accounts/templates/registration/password_reset/done.html
  project/accounts/templates/registration/password_reset/email.html
  project/accounts/templates/registration/password_reset/index.html
  project/accounts/urls.py
  project/accounts/views/account.py
  project/templates/includes/navbar.html
Labels: enhancement, frontend, backend, gpdr

#69 fix(test) not handling translation in account tests
  project/accounts/tests.py
Labels: bug

#78 feat(rides) ride detail view
  project/carpool/models.py
  project/carpool/templates/rides/detail.html
  project/templates/base.html
Labels: enhancement, frontend

#81 feat(ride) add pagination on `rides_list`
  project/carpool/forms.py
  project/carpool/templates/rides/detail.html
  project/carpool/templates/rides/list.html
  project/carpool/views.py
Labels: enhancement, frontend

#107 Add chat feature
  .env.dist
  .gitignore
  project/accounts/fixtures/users.json
  project/accounts/migrations/0001_initial.py
  project/accounts/migrations/0002_user_email_verified_alter_user_email.py
  project/accounts/models.py
  project/carpool/admin.py
  project/carpool/forms.py
  project/carpool/migrations/0001_initial.py
  project/carpool/models/__init__.py
  project/carpool/models/ride.py
  project/carpool/templates/rides/create.html
  project/carpool/templates/rides/detail.html
  project/carpool/templates/rides/list.html
  project/carpool/urls.py
  project/carpool/views.py
  project/chat/__init__.py
  project/chat/admin.py
  project/chat/apps.py
  project/chat/consumers.py
  project/chat/migrations/0001_initial.py
  project/chat/migrations/__init__.py
  project/chat/models.py
  project/chat/routing.py
  project/chat/templates/chat/includes/mod_profile.html
  project/chat/templates/chat/includes/sidebar.html
  project/chat/templates/chat/index.html
  project/chat/templates/chat/moderation/index.html
  project/chat/templates/chat/moderation/room.html
  project/chat/templates/chat/moderation/search.html
  project/chat/templates/chat/room.html
  project/chat/urls.py
  project/chat/views.py
  project/project/asgi.py
  project/project/settings.py
  project/project/urls.py
  project/templates/includes/navbar.html
  requirements.txt
Labels: enhancement, frontend, backend, chat

#110 add gunicorn to requirements
  requirements.txt
Labels: enhancement

#115 Django Messages Framework Integration
  project/accounts/views/profile.py
  project/templates/base.html
  project/templates/messages/container.html
  project/templates/messages/script.html
  project/templates/messages/toast.html
Labels: enhancement, frontend

#120 Add support for postgis database
  .env.dist
  .github/workflows/django.yml
  CONTRIBUTE
  project/carpool/migrations/0001_initial.py
  project/project/settings/development.py
  project/project/settings/production.py
  requirements.txt
Labels: enhancement, backend, ci/cd

#123 Search bar in rides list
  project/carpool/migrations/0001_initial.py
  project/carpool/models/ride.py
  project/carpool/templates/rides/detail.html
  project/carpool/templates/rides/list.html
  project/carpool/views.py
  project/chat/migrations/0001_initial.py
Labels: frontend, backend, routing

#132 Switch to UV, add unit tests and coverage, fix bug in PasswordResetForm
  .github/workflows/test.yml
  .python-version
  project/accounts/admin.py
  project/accounts/forms.py
  project/accounts/middleware.py
  project/accounts/migrations/0001_initial.py
  project/accounts/models.py
  project/accounts/tasks.py
  project/accounts/tests.py
  project/accounts/tests/__init__.py
  project/accounts/tests/factories.py
  project/accounts/tests/test_forms.py
  project/accounts/tests/test_middlewares.py
  project/accounts/tests/test_models.py
  project/accounts/tests/test_views.py
  project/accounts/tokens.py
  project/accounts/urls.py
  project/accounts/views/__init__.py
  project/accounts/views/profile.py
  project/accounts/views/verify_email.py
  project/carpool/admin.py
  project/carpool/forms.py
  project/carpool/migrations/0001_initial.py
  project/carpool/models/__init__.py
  project/carpool/models/ride.py
  project/carpool/tasks.py
  project/carpool/tests.py
  project/carpool/tests/__init__.py
  project/carpool/tests/test_templatetags.py
  project/carpool/urls.py
  project/carpool/views.py
  project/chat/admin.py
  project/chat/consumers.py
  project/chat/migrations/0001_initial.py
  project/chat/models.py
  project/chat/urls.py
  project/chat/views.py
  project/manage.py
  project/project/asgi.py
  project/project/settings/production.py
  project/project/urls.py
  project/project/wsgi.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  uv.lock
Labels: documentation, enhancement, frontend, backend, ci/cd

#134 Update CONTRIBUTE with uv instructions
  CONTRIBUTE
Labels: documentation

#138 Tests 100% coverage for chat app
  project/carpool/tests/factories.py
  project/chat/tests/__init__.py
  project/chat/tests/factories.py
  project/chat/tests/test_views.py
  project/chat/views.py
  project/project/celery.py
  pyproject.toml
Labels: bug, enhancement, backend, ci/cd

#133 fix131 - i18n for the detail card in map view
  project/carpool/templates/rides/map.html
Labels: frontend

#149 language selection
  project/project/settings/production.py
  project/project/urls.py
  project/templates/base.html
  project/templates/includes/navbar.html
Labels: enhancement, frontend

#151 remove using `null=True` for any CharField
  project/carpool/migrations/0002_alter_location_city_alter_location_street_and_more.py
  project/carpool/models/__init__.py
  project/carpool/models/ride.py
Labels: backend

#153 Use multiselectfields for Choicefield
  project/carpool/migrations/0001_initial.py
  project/carpool/migrations/0002_alter_location_city_alter_location_street_and_more.py
  project/carpool/models/ride.py
  project/carpool/views.py
  project/project/settings/production.py
  pyproject.toml
  uv.lock
Labels: frontend, backend
