Repository insaroule/insaroule, pull requests merged in 2025-04, with the labels that each got.

#19 Add instructions on how to contribute #18
  CONTRIBUTE
Labels: documentation

#20 Bump version
  CHANGELOG.md
  CONTRIBUTE
Labels: documentation

#30 Improve register template, fixes #42
  project/accounts/forms.py
  project/accounts/templates/register.html
Labels: enhancement

#32 feat(templates) add a base.html template to extends from
  project/accounts/templates/login.html
  project/accounts/templates/register.html
  project/templates/base.html
Labels: enhancement

#34 fix(models) missing migration
  project/carpool/admin.py
  project/carpool/migrations/0002_vehicle.py
  project/carpool/models.py
Labels: bug, enhancement, backend
